### ISSUE TITLE
从一个时间开始进行累加，累加的间隔是任意时间间隔

### ISSUE THREAD

**Issue by ashanzhu** [kennytm/dbgen#4]
目前遇到的问题是，在生成数据时，如果从一个时间开始累加1微秒，直到指定的时间结束，schema中编写表达式？
需要生成的数据示例：
2024-01-01 00:00:00.000001  #开始时间
2024-01-01 00:00:00.000002
2024-01-01 00:00:00.000003
...
2024-10-01 10:23:24.999999 #结束时间

如果生成数据只需要10条，那么到达10条之后就直接退出了，即便没有到达终止时间也退出。

**Comment by ashanzhu** [comment]
@kennytm 帮忙看下现在支持嘛？

**Comment by kennytm** [comment]
> 目前遇到的问题是，在生成数据时，如果从一个时间开始累加1微秒，直到指定的时间结束，schema中编写表达式？

```sql
{{ TIMESTAMP '2024-01-01' + INTERVAL rownum MILLISECOND }}
```

> 如果生成数据只需要10条，那么到达10条之后就直接退出了，即便没有到达终止时间也退出。

Just use the flags `-N 10` in CLI

**Comment by ashanzhu** [comment]
> > 目前遇到的问题是，在数据生成时，如果从一个时间开始累加1微秒，直到指定的时间结束，schema中编写表达式？
> 
> ```sql
> {{ TIMESTAMP '2024-01-01 00:00:00' + INTERVAL rownum MILLISECOND }}
> ```
> 
> > 如果生成数据只需要10条，那么到达10条之后就直接退出了，甚至没有到达终止时间也退出。
> 
> `-N 10`只需使用CLI 中的标志

完全解决了，🍗*100 ，:）
